server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id:
            uri:
            predicates:
              - name:
                args:
                  name:
                  regexp:
